package com.davis.ktprogram.model

import java.io.Serializable
import java.util.ArrayList

/**
 * Created by davis on 16/5/18.
 */
data class ProductDetail(
        var addtime: String? ,
        var edittime: String? ,
        var slock: String?,
        var iproductid: String?,
        var iphysicid: String?,
        var ishopphysicid: String?,
        var sphysicname: String?,
        var sphysicdes: String?,
        var itgclassid: String?,
        var fmarkerprice: String?,
        var fvipprice: String?,
        var fprice: String?,
        var isellnum: String?,
        var istoragenum: String?,
        var spicurl: String?,
        var sbigpicurl: String?,
        var scontentinfo: String?,
        var sfactoryname: String?,
        var iviewnum: String?,
        var icommnum: String?,
        var stype: String?,
        var daddtime: String?,
        var fprostand: String?,
        var sstandard: String?,
        var seffect: String?,
        var ivipstoragenum: String?,
        var icoinnum: String?,
        var dendtime: String?,
        var ipaytype: String?,
        var isendtype: String?,
        var sproductcode: String?,
        var sstorage: String?,
        var fcostprice: String?,
        var iallstoragenum: String?,
        var sprotype: String?,
        var iorder: String?,
        var sgifttype: String?,
        var sbuytype: String?,
        var sspreadtype: String?,
        var iwarnstore: String?,
        var ispreadcount: String?,
        var ireturncount: String?,
        var fspreadprice: String?,
        var icostcount: String?,
        var irootclassid: String?,
        var iclassid: String?,
        var isourcecount: String?,
        var spackage: String?,
        var itoprootid: String?,
        var sshelflife: String?,
        var svideourl: String?,
        var sbatchnumber: String?,
        var isendtime: String?,
        var stip: String?,
        var fcoinmoney: String?,
        var sfoodstuff: String?,
        var sapppeople: String?,
        var sphasegrams: String?,
        var scalories: String?,
        var staglist: String?,
        var itotalscore: String?,
        var sbrandname: String?,
        var sfeatures: String?,
        var specials: String?,
        var srequire: String?,
        var sprostandars: String?,
        var spronums: String?,
        var freduce: String?,
        var fprostate: String?,
        var fshopprice: String?,
        var classtype: String?,
        var forderby: String?,
        var joinprice: String?,
        var sletter: String?,
        var makingmethod: String?,
        var itag: String?,
        var mincount: Float = 0.toFloat(),
        var prostate: String?,
        var piclist: ArrayList<String> = ArrayList<String>(),

        var unptlist: String?,
        var ptlist: String?,
        var ptorder: String?): Serializable {}
